# Sowing Success: How Machine Learning Helps Farmers Select the Best Crops

![Farmer in a field](farmer_in_a_field.jpg)

Measuring essential soil metrics such as nitrogen, phosphorous, potassium levels, and pH value is an important aspect of assessing soil condition. However, it can be an expensive and time-consuming process, which can cause farmers to prioritize which metrics to measure based on their budget constraints.

Farmers have various options when it comes to deciding which crop to plant each season. Their primary objective is to maximize the yield of their crops, taking into account different factors. One crucial factor that affects crop growth is the condition of the soil in the field, which can be assessed by measuring basic elements such as nitrogen and potassium levels. Each crop has an ideal soil condition that ensures optimal growth and maximum yield.

A farmer reached out to you as a machine learning expert for assistance in selecting the best crop for his field. They've provided you with a dataset called `soil_measures.csv`, which contains:

- `"N"`: Nitrogen content ratio in the soil
- `"P"`: Phosphorous content ratio in the soil
- `"K"`: Potassium content ratio in the soil
- `"pH"` value of the soil
- `"crop"`: categorical values that contain various crops (target variable).

Each row in this dataset represents various measures of the soil in a particular field. Based on these measurements, the crop specified in the `"crop"` column is the optimal choice for that field.  

In this project, you will build multi-class classification models to predict the type of `"crop"` and identify the single most importance feature for predictive performance.

In [1]:
# All required libraries are imported here for you.
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

# Load the dataset
crops = pd.read_csv("soil_measures.csv")

# Write your code here
# Explore dataset
print(crops.info())
print(crops.head(15))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   N       2200 non-null   int64  
 1   P       2200 non-null   int64  
 2   K       2200 non-null   int64  
 3   ph      2200 non-null   float64
 4   crop    2200 non-null   object 
dtypes: float64(1), int64(3), object(1)
memory usage: 86.1+ KB
None
     N   P   K        ph  crop
0   90  42  43  6.502985  rice
1   85  58  41  7.038096  rice
2   60  55  44  7.840207  rice
3   74  35  40  6.980401  rice
4   78  42  42  7.628473  rice
5   69  37  42  7.073454  rice
6   69  55  38  5.700806  rice
7   94  53  40  5.718627  rice
8   89  54  38  6.685346  rice
9   68  58  38  6.336254  rice
10  91  53  40  5.386168  rice
11  90  46  42  7.502834  rice
12  78  58  44  5.108682  rice
13  93  56  36  6.984354  rice
14  94  50  37  6.948020  rice


In [2]:
# Explore possible values of crop
print(crops['crop'].unique())

['rice' 'maize' 'chickpea' 'kidneybeans' 'pigeonpeas' 'mothbeans'
 'mungbean' 'blackgram' 'lentil' 'pomegranate' 'banana' 'mango' 'grapes'
 'watermelon' 'muskmelon' 'apple' 'orange' 'papaya' 'coconut' 'cotton'
 'jute' 'coffee']


In [3]:
# Separate features from target variable into separate arrays
crops_fts = crops.drop(['crop'], axis=1)
crops_tgt = crops['crop']

# Describe features and target variable
print(crops_fts.describe())
print(crops_tgt.value_counts())

# Convert into NumPy arrays for train/test split
X = crops_fts.values
y = crops_tgt.values

                 N            P            K           ph
count  2200.000000  2200.000000  2200.000000  2200.000000
mean     50.551818    53.362727    48.149091     6.469480
std      36.917334    32.985883    50.647931     0.773938
min       0.000000     5.000000     5.000000     3.504752
25%      21.000000    28.000000    20.000000     5.971693
50%      37.000000    51.000000    32.000000     6.425045
75%      84.250000    68.000000    49.000000     6.923643
max     140.000000   145.000000   205.000000     9.935091
rice           100
maize          100
jute           100
cotton         100
coconut        100
papaya         100
orange         100
apple          100
muskmelon      100
watermelon     100
grapes         100
mango          100
banana         100
pomegranate    100
lentil         100
blackgram      100
mungbean       100
mothbeans      100
pigeonpeas     100
kidneybeans    100
chickpea       100
coffee         100
Name: crop, dtype: int64


In [4]:
# Create array for every feature name
features = [col for col in crops_fts.columns]
print(features)

# Create empty list to store scores for each feature
scores = []

# Train-test split with each feature
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=26)
print(X_train)
print(features.index('N'))

['N', 'P', 'K', 'ph']
[[111.           6.          53.           6.313513  ]
 [ 25.         143.         200.           6.02424879]
 [106.          10.          49.           6.35062374]
 ...
 [ 56.          59.          55.           6.55189264]
 [ 86.           6.          53.           6.92184789]
 [ 13.          61.          24.           7.62991025]]
0


In [5]:
# Establish loop to fit model for each feature
for ft in features:
    # Initialise Logistic Regression model
    lr = LogisticRegression(multi_class='multinomial')
    # Fit the model
    lr.fit(X_train[:, features.index(ft)].reshape(-1,1), y_train)
    # Predict results
    y_pred = lr.predict(X_test[:, features.index(ft)].reshape(-1,1))
    # Calculate F1 score
    score = metrics.f1_score(y_test, y_pred, average='weighted')
    # Append result to scores list
    scores.append(score)
print(scores)

[0.07091416840329798, 0.12922425948624536, 0.24623950519784604, 0.024457786580862638]


In [6]:
# Create full dictionary of scores
predictive_feature = {
    "{}".format(features[0]): scores[0],
    "{}".format(features[1]): scores[1],
    "{}".format(features[2]): scores[2],
    "{}".format(features[3]): scores[3],
}
print(predictive_feature)

best_predictive_feature = {
    "K": predictive_feature['K']
}
print(best_predictive_feature)

{'N': 0.07091416840329798, 'P': 0.12922425948624536, 'K': 0.24623950519784604, 'ph': 0.024457786580862638}
{'K': 0.24623950519784604}
